Add preview for LandingScreen
DroidKaigi/conference-app-2021 pull request #258
Opened 2021-03-03 12:25 UTC by sobaya-0141

## Issue
- close #247 

## Overview (Required)
- add a preview function for LandingScreen

## Links
-

## Screenshot
Before | After
:--: | :--:
<img src="" width="300" /> | <img src="https://user-images.githubusercontent.com/45986582/109805547-eecf3f00-7c66-11eb-8330-b92c3bc9aef0.png" width="300" />

2021-03-03 13:31 UTC, tomoya0x00 commented
👀

2021-03-03 13:41 UTC, tomoya0x00 requested changes
@sobaya-0141 Thanks for your challenge! Could you check my comments? 🙏

2021-03-03 13:41 UTC, tomoya0x00 commented on uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/LandingScreen.kt
> +fun PreviewFeedScreen() {
How do you think about changing to a more suitable name? 👀

2021-03-03 13:41 UTC, tomoya0x00 commented on uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/LandingScreen.kt
> +        ProvideFeedViewModel(viewModel = fakeFeedViewModel()) {
I think `ProvideFeedViewModel` is not needed.
Because `LandingScreen` doesn't require `FeedViewModel` 👍

2021-03-03 23:24 UTC, sobaya-0141 commented
thank you for your review
I’m sorry I didn't check it well enough.

I already fixed all review comments

2021-03-04 02:17 UTC, takahirom commented
Thank! LGTM 👍

2021-03-04 02:17 UTC, takahirom approved these changes

2021-03-04 02:18 UTC, merged